### ISSUE TITLE
UNet is not run with GPU

### ISSUE THREAD

**Issue by engineer1109** [leejet/stable-diffusion.cpp#125]
I found the CONV_2D ops are all running all the CPU. Neither CUDA or OpenCL.

**Comment by leejet** [comment]
Can you give a detailed log?

**Comment by engineer1109** [comment]
I found RTX4090 and GTX1660S is the same speed of sampling，and they are costing CPU a lot performance.
Then I search the code of the conv2d, and found that conv2d is only for CPU impl.
https://github.com/FSSRepo/ggml/blob/70474c6890c015b53dc10a2300ae35246cc73589/src/ggml-cuda.cu
There is no GPU impl about conv2d.
https://github.com/FSSRepo/ggml/blob/70474c6890c015b53dc10a2300ae35246cc73589/src/ggml.c
Here is the CPU conv2d.

**Comment by engineer1109** [comment]
Let me check again with latest version tomorrow.

**Comment by engineer1109** [comment]
Consider add clblast conv func to support OpenCL?

**Comment by leejet** [comment]
The conv_2d operation is divided into two steps: im2col and mul_mat. Hence, you won't find the implementation related to conv2d directly in ggml-cuda.cu.

**Comment by engineer1109** [comment]
forgot add -DSD_CUBLAS.  GGML_CUBLAS is no use.
