### ISSUE TITLE
Exception when delete StableDiffusion pointer

### ISSUE THREAD

**Issue by javaaiorg** [leejet/stable-diffusion.cpp#130]
Exception when delete StableDiffusion pointer: 
![image](https://github.com/leejet/stable-diffusion.cpp/assets/143949784/2fe178ed-16eb-4f0d-94ba-ab5cc4b0be31)

ggml_backend_buffer_t should be initialized with NULL: 
source file stable-diffusion.cpp have 5 places need change: 
line: 1364, 1365
line: 2286, 2287
line: 3516, 3517
line: 4187, 4188
line: 4626, 4617

![image](https://github.com/leejet/stable-diffusion.cpp/assets/143949784/81487886-e70a-4220-939e-1bb0087de9a0)

This exception not triggered every time, cause StableDiffusion's pointer usually be delete before process exit, sometimes process exit faster than delete be executed, will not triggered this exception.

**Comment by leejet** [comment]
Thank you for the feedback. The issue has now been fixed.

**Comment by javaaiorg** [comment]
.
