### ISSUE TITLE
C-API export seems to not work correctly

### ISSUE THREAD

**Issue by DarthAffe** [leejet/stable-diffusion.cpp#139]
Hey, great to see that a C-style API is now included.

Sadly I don't get it do build correctly. I'm currently using this command
 `cmake .. -DBUILD_SHARED_LIBS=ON -DSD_BUILD_EXAMPLES=OFF -DSD_CUBLAS=ON`
and it builds the dll, but it does not seem to export the functions correctly.

If I change `stable-diffusion.h` to always include `#define SD_API __declspec(dllexport)` it works fine.

Is there something I'm missing?

I also noticed, that the K-quants do not work - loading the model works, but calling txt2img prints 
`GGML_ASSERT: <trimmed>\stable-diffusion.cpp\ggml\src\ggml-cuda.cu:6817: false`
then crashes with error code 0xC0000409

**Comment by Green-Sky** [comment]
https://github.com/leejet/stable-diffusion.cpp/blob/f2e4d9793bbe0ec713c28cc55b123c68afd8db90/stable-diffusion.h#L4-L20

according to the code, both `SD_BUILD_SHARED_LIB` and `SD_BUILD_DLL` need to be defined. Both of which don't seem to be exposed as options in cmake (@leejet)

**Comment by leejet** [comment]
I haven't adapted it for building shared libraries yet.

**Comment by leejet** [comment]
It's been added now.

**Comment by DarthAffe** [comment]
Works great, thanks :)

**Comment by Cyberhan123** [comment]
this doesn't work on mac
