### ISSUE TITLE
rocBLAS error: {...}  No such file or directory for GPU arch : gfx1031

### ISSUE THREAD

**Issue by AlessandroMIlani** [leejet/stable-diffusion.cpp#160]
The full error at execution time (the compilation had no problems following the guide):
```
PS C:\Users\ale\Desktop\sd> ./sd -m ./sd-v1-4.ckpt -p "a lovely cat"

rocBLAS error: Cannot read C:\Program Files\AMD\ROCm\5.7\bin\/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1031

rocBLAS error: Could not initialize Tensile host:
regex_error(error_backref): The expression contained an invalid back reference.
```
If I understand correctly, my gpu rx6750xt it's not directly supported from rocblas.
On linux, a similar problem with rocm can be resolved with the definition of the env variable HSA_OVERRIDE_GFX_VERSION = 10.3.0.
Is there already something similar for windows or is the situation still too immature?

**Comment by mchome** [comment]
Wait for vulkan backend, rocm is joke on team red.

**Comment by wdx04** [comment]
To use rocBLAS with an unsupported GPU on Windows you have to build rocBLAS from source. It's not too hard if you follow the steps:
https://www.reddit.com/r/LocalLLaMA/comments/16d1hi0/guide_build_llamacpp_on_windows_with_amd_gpus_and/

**Comment by wdx04** [comment]
For your convenience, I have built the rocBLAS library with gfx803, gfx900, gfx1010, gfx1031, gfx1032 support, using the HIP 5.7.1 SDK.
https://1drv.ms/u/s!ApduJQeHcf7MgfMKUM3PC1T-jqDIIA?e=qnWLHT

**Comment by AlessandroMIlani** [comment]
> For your convenience, I have built the rocBLAS library with gfx803, gfx900, gfx1010, gfx1031, gfx1032 support, using the HIP 5.7.1 SDK. https://1drv.ms/u/s!ApduJQeHcf7MgfMKUM3PC1T-jqDIIA?e=qnWLHT

Tanks for the file, I've tried to replace it in /ROCm/5.7/bin, then compiled and execute sd, but still not work: `(regex_error(error_backref): The expression contained an invalid back reference.)`
Probably the dll file is not all what is missing in my configuration. So as soon as I have time I will try to compile rocBLAS from source

**Comment by wdx04** [comment]
> > For your convenience, I have built the rocBLAS library with gfx803, gfx900, gfx1010, gfx1031, gfx1032 support, using the HIP 5.7.1 SDK. https://1drv.ms/u/s!ApduJQeHcf7MgfMKUM3PC1T-jqDIIA?e=qnWLHT
> 
> Tanks for the file, I've tried to replace it in /ROCm/5.7/bin, then compiled and execute sd, but still not work: `(regex_error(error_backref): The expression contained an invalid back reference.)` Probably the dll file is not all what is missing in my configuration. So as soon as I have time I will try to compile rocBLAS from source
Yes, the rocBLAS library files are also needed to be placed in /ROCm/5.7/bin, you can get it here:
https://1drv.ms/u/s!ApduJQeHcf7MgfMMIctu47Cs05ROxg?e=jRoh8F
Hope this helps!

**Comment by AlessandroMIlani** [comment]
> > > For your convenience, I have built the rocBLAS library with gfx803, gfx900, gfx1010, gfx1031, gfx1032 support, using the HIP 5.7.1 SDK. https://1drv.ms/u/s!ApduJQeHcf7MgfMKUM3PC1T-jqDIIA?e=qnWLHT
> > 
> > 
> > Tanks for the file, I've tried to replace it in /ROCm/5.7/bin, then compiled and execute sd, but still not work: `(regex_error(error_backref): The expression contained an invalid back reference.)` Probably the dll file is not all what is missing in my configuration. So as soon as I have time I will try to compile rocBLAS from source
> > Yes, the rocBLAS library files are also needed to be placed in /ROCm/5.7/bin, you can get it here:
> > https://1drv.ms/u/s!ApduJQeHcf7MgfMMIctu47Cs05ROxg?e=jRoh8F
> > Hope this helps!

Thanks, now work.
For the moment, times are similar to direct ml (1.8 t/s for sd 1.4 at 512x512 and 3.9 s/t for 1024x1024. without other setting, all default).
For the quality, it seems that the same prompt gives worse results than directml, but I haven't done enough testing to be sure yet
