### ISSUE TITLE
SD build static libggml.dylib 

### ISSUE THREAD

**Issue by phudtran** [leejet/stable-diffusion.cpp#184]
Hi when using the latest release, the SD binary now requires libggml.dylib to be in the same folder.

<img width="530" alt="image" src="https://github.com/leejet/stable-diffusion.cpp/assets/22720475/a6de5701-aa33-4654-b8b9-6ce6b91deb63">

Is there a way to bake it into the binary?

**Comment by leejet** [comment]
Try this modification and see if it works?

```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -77,6 +77,7 @@ if(SD_BUILD_SHARED_LIBS)
     set(CMAKE_POSITION_INDEPENDENT_CODE ON)
 else()
     message("Build static library")
+    set(BUILD_SHARED_LIBS OFF)
     add_library(${SD_LIB} STATIC ${SD_LIB_SOURCES})
 endif()
```

**Comment by phudtran** [comment]
It works! I created #188 for this.
