### ISSUE TITLE
Windows x64 executable for stable-diffusion.cpp

### ISSUE THREAD

**Issue by JohnClaw** [leejet/stable-diffusion.cpp#19]
I tried to compile your app using cmake but encountered an error. I'm a newbie and know nothing about c and c++ compilation. Could you make a binary release for Windows, please?

P.S: Cmake's error was "Invalid character escape '\M'".

**Comment by vxiiduu** [comment]
Yeah, .exe release definitely necessary.

**Comment by leejet** [comment]
I followed the example of llama.cpp and created a release through the CI process. You can now download the Windows x64 binary from https://github.com/leejet/stable-diffusion.cpp/releases.

**Comment by JohnClaw** [comment]
Thank you very much.

**Comment by leejet** [comment]
Windows x64 executable has been added.
