### ISSUE TITLE
StableDiffusionGGML buffer problem : call txt2img twice

### ISSUE THREAD

**Issue by piallai** [leejet/stable-diffusion.cpp#202]
Hello. First of all, thank you very much for your work.

I'd like to be able to call <code>txt2img</code> twice, without neededing to release the memory model calling <code>free_sd_ctx(sd_ctx)</code>.
When doing so, the program crashes in <code>ggml_backend_cuda_graph_compute</code>

```
Assertion failed: node->src[j]->buffer->buft == ggml_backend_cuda_buffer_type(cuda_ctx->device) || ggml_backend_buffer_is_cuda_split(node->src[j]->buffer), file C:\***\stable-diffusion.cpp-master-a469688\ggml\src\ggml-cuda.cu, line 12267
```

It seems <code>txt2img</code> function (and probably also <code>img2img</code>) is altering the buffer management of  <code>StableDiffusionGGML</code>, and using the <code>StableDiffusionGGML</code> instance a second time is not possible as is.

Is it intended, or could it be fixed?

**Comment by fszontagh** [comment]
hi @piallai!

Did you set the "_free_params_immediately_" to _false_ when you load the model in _new_sd_ctx_?
