### ISSUE TITLE
Problems with smaller images

### ISSUE THREAD

**Issue by fwsGonzo** [leejet/stable-diffusion.cpp#24]
Hey, I am using this repo successfully in a very strange single-threaded environment, and it's working. Great work! I really love the idea of a CPU-based generator that can be both single-threaded and statically built. One problem that I have though is that images smaller than 512x512 seems to be failing all the time. This issue also happens in a regular Linux terminal. Example:

```
$ ./build/bin/sd -m models/sd-v1-4-ggml-model-q4_1.bin -W 256 -H 256 --seed 42 --steps 12 -p "A lovely cat, high quality" -o 
sd.png

Option: 
    n_threads:       16
    mode:            txt2img
    model_path:      models/sd-v1-4-ggml-model-q4_1.bin
    output_path:     sd.png
    init_img:        
    prompt:          A lovely cat, high quality
    negative_prompt: 
    cfg_scale:       7.00
    width:           128
    height:          128
    sample_method:   eular a
    sample_steps:    12
    strength:        0.75
    seed:            42
System Info: 
    BLAS = 0
    SSE3 = 1
    AVX = 1
    AVX2 = 1
    AVX512 = 0
    AVX512_VBMI = 0
    AVX512_VNNI = 0
    FMA = 1
    NEON = 0
    ARM_FMA = 0
    F16C = 1
    FP16_VA = 0
    WASM_SIMD = 0
    VSX = 0
```
![sd](https://github.com/leejet/stable-diffusion.cpp/assets/3758947/d229a1c1-800f-4992-b08d-451c2047bbde)

```
$ ./build/bin/sd -m models/sd-v1-4-ggml-model-q4_1.bin -W 128 -H 128 --seed 42 --steps 12 -p "A lovely cat, high quality" -o sd.png
```
![sd](https://github.com/leejet/stable-diffusion.cpp/assets/3758947/1b595991-13e1-454c-8886-c94fc28a95ab)

```
$ ./build/bin/sd -v -m models/sd-v1-4-ggml-model-q4_1.bin -W 512 -H 512 --seed 42 --steps 12 -p "A lovely cat, high quality" -o sd.png
```
![sd](https://github.com/leejet/stable-diffusion.cpp/assets/3758947/46ef7338-bf31-44c6-b597-11f86b09428d)

These images were created on my AMD Ryzen 9 7950X machine. I am looking into this problem now, just creating this issue to track the problem.

Changing models doesn't help. I am experimenting with -march settings now.

**Comment by ClashSAN** [comment]
It's the model itself, test: you'll see this is the same across different libraries.



Only certain finetuned models work well at a smaller size:

 ![cat2](https://github.com/leejet/stable-diffusion.cpp/assets/98228077/1346a8bd-da56-424d-a81b-adf0c1aab940)

these seem to work well at that range:

https://huggingface.co/justinpinkney/miniSD/blob/main/miniSD.ckpt
https://huggingface.co/cag/anything-v3-1/blob/main/anything-v3-1.ckpt

But just like generating 512x512 with the base sdxl model produces bad images, generating with 192x192 or below often won't work out, try 384x384 with the base model.

**Comment by fwsGonzo** [comment]
Thanks, that was the solution. It works well now! :)
