### ISSUE TITLE
Vulkan support

### ISSUE THREAD

**Issue by SkutteOleg** [leejet/stable-diffusion.cpp#256]
### Discussed in https://github.com/leejet/stable-diffusion.cpp/discussions/240

<div type='discussions-op-text'>

<sup>Originally posted by **SkutteOleg** April 26, 2024</sup>
Is Vulkan support planned?</div>

Is Vulkan support feasible? How far away is it?
![image](https://github.com/leejet/stable-diffusion.cpp/assets/45887963/97556938-4364-4bff-af4b-b30f161ca37b)

**Comment by grauho** [comment]
Looks like you've already tried to patch in some Vulkan back-end support, mind posting your fork?

**Comment by sil2193** [comment]
@leejet this will help a ton, is there any plan for this?

**Comment by jparismorgan** [comment]
@grauho maybe this will help? I saw it on a different fork: https://github.com/leejet/stable-diffusion.cpp/compare/master...Cloudwalk9:stable-diffusion.cpp:master

**Comment by SkutteOleg** [comment]
> @grauho maybe this will help? I saw it on a different fork: [master...Cloudwalk9:stable-diffusion.cpp:master](https://github.com/leejet/stable-diffusion.cpp/compare/master...Cloudwalk9:stable-diffusion.cpp:master)

#291

**Comment by SkutteOleg** [comment]
Resolved by #291
