### ISSUE TITLE
Feature request: Exif metadata

### ISSUE THREAD

**Issue by h3ndrik** [leejet/stable-diffusion.cpp#26]
I think it's a great feature that tools like automatic1111 write all the parameters from inference into the images' metadata. That way you can re-discover old pictures on your harddrive and see what model hash, seed and prompt you used.

The Readme of the stb library mentiones this small lib:
* https://github.com/mayanklahiri/easyexif

(Edit: I think that library is just to read metadata, not write it :disappointed: )

**Comment by leejet** [comment]
In fact, I'm considering adding parameter information to the generated images. However, I haven't found a good method for doing so yet.

**Comment by Green-Sky** [comment]
I think we should be able to "write" the image to memory (using `stb_image_write`) and modify the memory afterwards to insert a `tEXt` chunk (automatic's ui inserts them at the front after `IHDR`)

[wikipedia excerpt](https://en.wikipedia.org/wiki/PNG#Ancillary_chunks):
> `tEXt` can store text that can be represented in [ISO/IEC 8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1), with one [key-value](https://en.wikipedia.org/wiki/Attribute%E2%80%93value_pair) pair for each chunk. The "key" must be between one and 79 characters long. Separator is a null character. The "value" can be any length, including zero up to the maximum permissible chunk size minus the length of the keyword and separator. Neither "key" nor "value" can contain null character. Leading or trailing spaces are also disallowed.

example hex screencap from file generated with automatic's ui:
![image](https://github.com/leejet/stable-diffusion.cpp/assets/2938071/6d551c87-543a-4025-9c10-d32a1c4a58a5)
