### ISSUE TITLE
Support PCM Weights

### ISSUE THREAD

**Issue by shibingli** [leejet/stable-diffusion.cpp#290]
Support PCM Weights?

https://huggingface.co/wangfuyun/PCM_Weights

**Comment by Green-Sky** [comment]
Looks like the loras should just work. (beside the 1-step one)

**Comment by shibingli** [comment]
Thank you, I will test it out!

**Comment by razvanab** [comment]
> Thank you, I will test it out!

Did you try it?  Can you please post the command for it if it worked?
