### ISSUE TITLE
GGUF-converted LORAs are not able to be used.

### ISSUE THREAD

**Issue by HAV0X1014** [leejet/stable-diffusion.cpp#307]
I am not sure if this is supported, however a GGUF converted LORA is not able to be used with text2image. The LORA itself seems to convert and quantize well, however it is not recognized by text2image as a valid LORA. An example of what is output is below.
```
[INFO ] stable-diffusion.cpp:556  - Attempting to apply 1 LoRAs
[WARN ] stable-diffusion.cpp:518  - can not find LORA_NAME.safetensors or LORA_NAME.ckpt for lora LORA_NAME
[INFO ] stable-diffusion.cpp:1203 - apply_loras completed, taking 0.00s
```
I am very new to this project, and I am unaware if this is intentional behavior or a potential area for expansion. Thank you for all of your work!

**Comment by grauho** [comment]
Currently only safetensors and checkpoint files are supported for LoRAs. Precision in LoRAs is very important so it's likely one wouldn't get as reliable results if using a quantized gguf LoRA. If one wanted to try anyway one could remove the filename extension check in the "apply_lora" function as the LoRA loading logic calls "init_from_file" which should be able to handle gguf files just like the primary model loader but it's possible there will be other pitfalls.
