### ISSUE TITLE
v-prediction support

### ISSUE THREAD

**Issue by daniandtheweb** [leejet/stable-diffusion.cpp#325]
Right now the program seems to only support eps-prediction. Some models use v-prediction and the lack of support for it causes the inference to generate noisy and unusable images with those models.

EDIT: it seems like there's support for it but the detection for stable diffusion 1.X isn't implemented.

**Comment by leejet** [comment]
Which sd1.x models use v-prediction?

**Comment by daniandtheweb** [comment]
Mainly the yiffymix models but I've found other 1.5 experimental models that use it that I can't remember right now.

Since there aren't a lot of models using it maybe an option to force the denoising mode manually would be enough.
