### ISSUE TITLE
Bug: Clip-L does absolutely nothing with Flux models.

### ISSUE THREAD

**Issue by stduhpf** [leejet/stable-diffusion.cpp#396]
I was testing out alternative clip models for Flux (https://huggingface.co/zer0int/CLIP-GmP-ViT-L-14), and noticed the output were oddly similar to the ones I was getting with the original clip-l. 
Turns out the result are actually 100% identical (when using the same seed of course), not even a single bit of difference. Using the same models with ComfyUI does lead to noticably different outputs (with fixed seed).

|  | clip-L |  ViT-L-14 |
| - | - | - |
| Dev q3_k (sd.cpp) | ![test-dev-clip](https://github.com/user-attachments/assets/84b921d7-62c7-4251-ba68-f73ac60d5057) | ![test-dev-vit](https://github.com/user-attachments/assets/c7824e1d-cab0-4460-9513-97a51548bc8a) |
| Schnell q3_k  (sd.cpp) | ![test-schnell-clip](https://github.com/user-attachments/assets/fdfab0f1-4160-4174-93bf-e4aedecfbef2) | ![test-schnell-vit](https://github.com/user-attachments/assets/77f9bb03-26c5-4f0a-a1d5-c0685e5193bf) |
| Schnell fp8 (Comfyui) | ![ComfyUI_00515_](https://github.com/user-attachments/assets/524c01a0-23c5-4dc2-8bb6-ed73d427549f) | ![ComfyUI_00514_](https://github.com/user-attachments/assets/a90cce3a-a323-4c26-b8cf-91f29ae26e4e) |
| Schnell q3_k (Comfyui) | ![ComfyUI_00517_](https://github.com/user-attachments/assets/6ad61f77-879e-43cd-a691-25ebd2d9c6bb) | ![ComfyUI_00516_](https://github.com/user-attachments/assets/b395f1c9-889d-4abf-8169-9a97c5b5f164) |

As a sidenote, this could explain why I was feeling like the generations I get with sdcpp look less detailed and more artifacty than when I'm using ComfyUI at the same quants.

**Comment by Green-Sky** [comment]
You are right, it is commented out and just set to 0.
https://github.com/leejet/stable-diffusion.cpp/blob/14206fd48832ab600d9db75f15acb5062ae2c296/conditioner.hpp#L1107-L1121
