### ISSUE TITLE
stable-diffusion.dll is much larger now (14MB vs. 140MB)

### ISSUE THREAD

**Issue by Jonathhhan** [leejet/stable-diffusion.cpp#408]
The June 1st release was the last one with the smaller size of 14MB, the June 28th release already has 140MB. I wonder, if it is neccesary, that the size increased that much and why, if so...

**Comment by Jonathhhan** [comment]
Anyway, not really an issue, if it needs to be that big.

**Comment by Green-Sky** [comment]
I am assuming this is concerning cuda builds? yea upstream ggml got huge, since it contains specialized assembly for multiple platforms.
(also a duplicate of https://github.com/leejet/stable-diffusion.cpp/issues/311 :) )
