### ISSUE TITLE
Use as a dependency

### ISSUE THREAD

**Issue by kikoferrer** [leejet/stable-diffusion.cpp#415]
Is it possible to use this as a dependency for my code? Like python for example similar to how llama.cpp can be used as a dependency? Thanks

**Comment by SkutteOleg** [comment]
I'm not familiar with with python too much but you'd probably need python bindings just like with other languages.

**Comment by SkutteOleg** [comment]
https://github.com/william-murray1204/stable-diffusion-cpp-python
