### ISSUE TITLE
Run as a server

### ISSUE THREAD

**Issue by razvanab** [leejet/stable-diffusion.cpp#419]
Can I run stable-diffusion.cpp as a server?
If not, do you plan to implement this?

**Comment by stduhpf** [comment]
You can try this: https://github.com/leejet/stable-diffusion.cpp/pull/367
This is very experimental though, there is no nice API, but it allows to send different prompts without reloading the models every time.

**Comment by razvanab** [comment]
sd-server is your fork of stable-diffusion.cpp ?

**Comment by stduhpf** [comment]
Yes.

**Comment by razvanab** [comment]
It's working 
Thanks.

**Comment by CrushDemo01** [comment]
> Yes.

Hello, I found an error.
```
error: unknown argument: --taesd
usage: /text2img/serve_sdcpp/stable-diffusion.cpp/build/bin/sd-server [arguments]
```
Request support for this parameter. Thanks.

**Comment by nonetrix** [comment]
This would make making UIs a lot easier, I might try making a simple one after something like this is done
