### ISSUE TITLE
Don't use STL containers in DLL interface

### ISSUE THREAD

**Issue by AonekoSS** [leejet/stable-diffusion.cpp#477]
We can't call it in other implementation or languages.

argument for skip layer guidance
`std::vector<int> skip_layers = {},`
https://github.com/leejet/stable-diffusion.cpp/blob/master/stable-diffusion.h#L169
https://github.com/leejet/stable-diffusion.cpp/blob/master/stable-diffusion.h#L193

**Comment by stduhpf** [comment]
Oops
