### ISSUE TITLE
SD3/3.5 issues with new releases

### ISSUE THREAD

**Issue by stduhpf** [leejet/stable-diffusion.cpp#479]
Since the recent update , SD 3.5 generated images look a bit burned out compared to images generated with the exact same parameters with the previous versions. This happens both with CPU and Vulkan backends (can't test the others). Looks like a VAE problem to me, since the image composition is almost exactly the same. 

Also sd3 images are pitch black when using to the more recent version of GGML on Vulkan (on CPU it is just burned in like with sd3.5). 

| model | master (c3eeb669cd9b942ec4b66ed3d0bf28b42b1f9c28) | before ggml update (b5f4932) | ac54e00 with #451 and #397 merged |
| --- | --- | --- | --- |
| sd 3.5 medium | ![output](https://github.com/user-attachments/assets/99d5b310-f2d8-4826-896e-8e2080df5bbb) | ![output](https://github.com/user-attachments/assets/d6816f72-7569-4f6a-9de7-c68512509abb) | ![skiplayercfg](https://github.com/user-attachments/assets/9fa59405-097d-4d1f-a0e7-d3ee6ffa31b2) |
| sd 3.5 large turbo | ![output](https://github.com/user-attachments/assets/73977064-73ee-488e-89fb-dbc3a3b112ca) | ![output](https://github.com/user-attachments/assets/a3127288-6d5c-4c68-8af4-48c22da394fb) | ![output](https://github.com/user-attachments/assets/2d1c9f6c-6d95-483d-a942-c05845afa7b3) |
| sd 3 medium | ![output](https://github.com/user-attachments/assets/21a92d66-9155-4a30-8d3a-65294780cd02) | ![output](https://github.com/user-attachments/assets/5da47731-6ecc-4fa8-bea8-c8af1d4baa18) | ![output](https://github.com/user-attachments/assets/9e04b44c-d94d-439d-893d-4379a1b2594b) |

**Comment by stduhpf** [comment]
Git bisect result:

1c168d98a5a47aaf6d9b2c7f3a23e3166c59a6ec is the first bad commit
commit 1c168d98a5a47aaf6d9b2c7f3a23e3166c59a6ec (HEAD, tag: master-1c168d9)
Author: Erik Scholz <Green-Sky@users.noreply.github.com>
Date:   Sat Nov 23 05:39:08 2024 +0100

    fix: repair flash attention support (#386)

    * repair flash attention in _ext
    this does not fix the currently broken fa behind the define, which is only used by VAE

    Co-authored-by: FSSRepo <FSSRepo@users.noreply.github.com>

    * make flash attention in the diffusion model a runtime flag
    no support for sd3 or video

    * remove old flash attention option and switch vae over to attn_ext

    * update docs

    * format code

    ---------

    Co-authored-by: FSSRepo <FSSRepo@users.noreply.github.com>
    Co-authored-by: leejet <leejet714@gmail.com>

 CMakeLists.txt        |   6 --
 README.md             |  21 +++-
 clip.hpp              |  18 ++--
 common.hpp            |  23 ++--
 conditioner.hpp       |  19 ++--
 diffusion_model.hpp   |  12 ++-
 examples/cli/main.cpp |  10 +-
 flux.hpp              |  49 ++++++---
 ggml_extend.hpp       |  77 ++++++-------
 model.cpp             |  28 +++--
 model.h               |   2 +-
 pmid.hpp              | 293 +++++++++++++++++++++++---------------------------
 stable-diffusion.cpp  |  61 ++++++-----
 stable-diffusion.h    |   3 +-
 unet.hpp              |  11 +-
 util.cpp              |   5 +-
 vae.hpp               |  10 +-
 17 files changed, 334 insertions(+), 314 deletions(-)

  @Green-Sky Do you have a clue what change could be the root cause?

**Comment by Green-Sky** [comment]
Damn. Yea I refactored the attention. However, the non-flash-attn code should be equivalent. See the changes in ggml_extend.hpp .
Can you play around with that? I don't have sd3 handy rn.

**Comment by Green-Sky** [comment]
Oh, maybe its vae

https://github.com/leejet/stable-diffusion.cpp/commit/1c168d98a5a47aaf6d9b2c7f3a23e3166c59a6ec#diff-b2cfbe45be6080d9958c6c3b55c2f8792413f7088274ffc2bd6cc6e47945a183L100-L108

**Comment by leejet** [comment]
I think it's the issue with `ggml_nn_attention_ext` used by VAE, I've reverted the relevant changes, you can try again.

**Comment by Green-Sky** [comment]
Hm, I wonder what went wrong there. I tried to unify the attention, and it worked for every model I tested...

**Comment by stduhpf** [comment]
@leejet Yes, 4570715727f35e5a07a76796d823824c8f42206c fixed the burn in issue. sd3 is still black on vulkan, but that probably comes from ggml upstream.

**Comment by stduhpf** [comment]
@Green-Sky I don't exactly know what I'm doing, but I just managed to fix it on on my end by just setting `skip_reshape`to `false` when calling `ggml_nn_attention_ext()`in vae. Was it set to `true` for a reason?

```diff
diff --git a/vae.hpp b/vae.hpp
index 0c7d84f..622a1d9 100644
--- a/vae.hpp
+++ b/vae.hpp
@@ -104,7 +104,7 @@ public:
         v      = ggml_reshape_3d(ctx, v, c, h * w, n);              // [N, h * w, in_channels]

         // h_ = ggml_nn_attention(ctx, q, k, v, false);  // [N, h * w, in_channels]
-        h_ = ggml_nn_attention_ext(ctx, q, k, v, 1, nullptr, false, true, false);
+        h_ = ggml_nn_attention_ext(ctx, q, k, v, 1, nullptr, false, false, false);
```

**Comment by Green-Sky** [comment]
> @Green-Sky I don't exactly know what I'm doing, but I just managed to fix it on on my end by just setting `skip_reshape`to `false` when calling `ggml_nn_attention_ext()`in vae.


Oh, thats nice, did you test other models too?


> Was it set to `true` for a reason?

I honestly dont remember. I will do more test later.

**Comment by stduhpf** [comment]
> Oh, thats nice, did you test other models too?

Flux Lite and SDXL seem to work, so i'd assume everything should be fine.

**Comment by stduhpf** [comment]
Also the black image with SD3 on Vulkan isn't a VAE issue. I tried with #454, and the previews were also black. I'll try to see if I can figure out what is going on here.

**Comment by stduhpf** [comment]
Ok, that is kinda funny. The SD3 issue is actually related to another issue I already reported in llama.cpp (https://github.com/ggerganov/llama.cpp/issues/10434), and https://github.com/ggerganov/llama.cpp/pull/10437 fixed it.
