### ISSUE TITLE
stable diffusion cpp and hyper.sd sd3

### ISSUE THREAD

**Issue by michelgirault** [leejet/stable-diffusion.cpp#483]
hi, I'm trying to run hypersd sd3 8 steps (see bellow) without any success
https://huggingface.co/ByteDance/Hyper-SD/resolve/main/Hyper-SD3-8steps-CFG-lora.safetensors

i was wondering if someone was successful? i understand you have to fuse the lora with the base model

thanks

**Comment by stduhpf** [comment]
It's just a lora, in theory it should work like any other Lora, but here, it's using the _A/_B convention (instead of _up/_down), which is not supported yet. (see #370).
Maybe you can tray merging the lora into the model with another tool and then use the merge instead of the base model?

**Comment by michelgirault** [comment]
thanks for the feedback, i will try like that
