### ISSUE TITLE
Build failing with Metal

### ISSUE THREAD

**Issue by grorge123** [leejet/stable-diffusion.cpp#512]
When I update to the newest commit [9578fdc](https://github.com/leejet/stable-diffusion.cpp/commit/9578fdcc4632dc3de5565f28e2fb16b7c18f8d48), I encounter the build issue for metal. But it works for no metal or cuda.

- Compile command
```
cmake .. -DSD_METAL=ON
cmake --build . --config Release
```

- Cmake error message
```
stable-diffusion.cpp/./ggml_extend.hpp:1143:13: error: use of undeclared identifier 'ggml_backend_metal_set_n_cb'
            ggml_backend_metal_set_n_cb(backend, n_threads);

stable-diffusion.cpp/stable-diffusion.cpp:164:9: error: use of undeclared identifier 'ggml_backend_metal_log_set_callback'
        ggml_backend_metal_log_set_callback(ggml_log_callback_default, nullptr);

```

**Comment by stduhpf** [comment]
I can confirm. I think it could be related to the fact that `ggml-metal.m` was moved from `ggml/src/` to `ggml/src/ggml-metal/`
(https://github.com/ggerganov/ggml/commit/813a12ce9edc1f908f1af69aacd54182005d9d4c, https://github.com/ggerganov/ggml/commit/a131a8200aac68500a44b5068705548db4bd2617)

**Comment by stduhpf** [comment]
I can build by replacing references to `ggml_backend_metal_log_set_callback()` with `ggml_log_set()` and commenting out the call to `ggml_backend_metal_set_n_cb()`. I couldn't find what to replace it with.
