### ISSUE TITLE
GGML OpenCL Type Error

### ISSUE THREAD

**Issue by engineer1109** [leejet/stable-diffusion.cpp#73]
Your GGML repo has opencl bug.
https://github.com/leejet/ggml/pull/1
fix size type error
sizeof(ggml_fp16_t) is error
should be sizeof(float)

https://github.com/leejet/ggml/pull/1/files

**Comment by leejet** [comment]
Thank you for your contribution, but I believe the upstream GGML has already fixed this issue. I will sync the changes from the upstream repository to my fork, so that pull request will not be merged.

**Comment by engineer1109** [comment]
fixed
