### ISSUE TITLE
flash attention leads to error

### ISSUE THREAD

**Issue by rayrayraykk** [leejet/stable-diffusion.cpp#74]
I try to use `ggml_flash_attn` to accelerate the process, so I replace `ggml_mul_mat` in `cross-attention` in UNET in stable-diffusion.cpp:
```C++
...
#if 1
                struct ggml_tensor * kqv = ggml_flash_attn(ctx, q, k, v, true);
#else
                struct ggml_tensor* kq = ggml_mul_mat(ctx, k, q);  // [N * n_head, h * w, h * w]
                // kq = ggml_diag_mask_inf_inplace(ctx, kq, 0);
                kq = ggml_soft_max_inplace(ctx, kq);

                struct ggml_tensor* kqv = ggml_mul_mat(ctx, v, kq);  // [N * n_head, h * w, d_head]
#endif
...
```

But it leads to an error. Looks like the `max_position = 2`, `N = 64`, and `const int64_t P = nek1 - N;` which is less than `0`. Can someone help me? Great thx!

**Comment by Green-Sky** [comment]
Did you observe any speed improvement?

**Comment by FSSRepo** [comment]
@rayrayraykk I will see if after finishing my pull request for adding the CUDA backend, I will work on using flash attention v2 and improving the conv2d algorithm with FFT. Additionally, there is a new recent paper that allows using tensor cores to accelerate convolutions in CUDA. The truth is that I don't have enough knowledge to interpret equations from papers into code, which makes it somewhat difficult for me to implement things.
