### ISSUE TITLE
Error while loading weight

### ISSUE THREAD

**Issue by juniofaathir** [leejet/stable-diffusion.cpp#8]
I got this error while loading the models
```
[INFO]  stable-diffusion.cpp:2500 - loading model from '/path/to/models/meichidarkMix_meichidarkV4-ggml-model-q4_0.bin'
[DEBUG] stable-diffusion.cpp:2508 - verifying magic
[DEBUG] stable-diffusion.cpp:2519 - loading hparams
[INFO]  stable-diffusion.cpp:2525 - ftype: q4_0
[DEBUG] stable-diffusion.cpp:2531 - loading vocab
[DEBUG] stable-diffusion.cpp:2569 - ggml tensor size = 240 bytes
[INFO]  stable-diffusion.cpp:2570 - params ctx size =  1431.33 MB
[DEBUG] stable-diffusion.cpp:2587 - preparing memory for the weights
[DEBUG] stable-diffusion.cpp:2602 - loading weights
[WARN]  stable-diffusion.cpp:2650 - unknown tensor 'control_model.input_blocks.0.0.bias' in model file
[WARN]  stable-diffusion.cpp:2650 - unknown tensor 'control_model.input_blocks.0.0.weight' in model file
[WARN]  stable-diffusion.cpp:2650 - unknown tensor 'control_model.input_blocks.1.0.emb_layers.1.bias' in model file
[WARN]  stable-diffusion.cpp:2650 - unknown tensor 'control_model.input_blocks.1.0.emb_layers.1.weight' in model file
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
Aborted (core dumped)
```
I'm using Intel i5-8250U laptop with Ubuntu, RAM 12GB
Am I doing wrong while converting and quantizing the model or... ?

Thank you

**Comment by leejet** [comment]
The format of meichidarkMix_meichidarkV4.safetensors is different from the original SD 1.x and currently not compatible. I'll look into how to make it compatible later on.

**Comment by juniofaathir** [comment]
Ah I see
So, it means currently only support the SD 1.4 & 1.5 models?

Btw.. Love your works man!

**Comment by leejet** [comment]
Yes, models that contain control model or lora weights are not supported yet

**Comment by leejet** [comment]
> Ah okay. I ran into this problem with a few other models. I hope this isn't too complicated. Can you add that to the ToDo list?

Now it's been added to TODO list.

**Comment by leejet** [comment]
@juniofaathir @h3ndrik  This issue has been resolved. You can pull the latest code, reconvert the weight files, and rebuild the SD executable to fix this problem.

**Comment by leejet** [comment]
I've tested it with meichidarkMix and there are no issues.

```
./bin/sd -m ../models/meichidarkMix_meichidarkV4-ggml-model-q4_0.bin -p "1girl,ultra detailed 8k cg, masterpieces, best quality,pureerosface_v1,black hair,jk,black pantyhose,loafers, plaid skirt, black_footwear,school uniform,looking at viewer,class,day" -n "(worst quality, low quality:1.4), logo, watermark, signature, text, easynegative" -v
```



![output](https://github.com/leejet/stable-diffusion.cpp/assets/31925346/94a84a3c-1e75-4d98-b636-0fbe8cd8b17b)
