### ISSUE TITLE
Support clip skip

### ISSUE THREAD

**Issue by imikod** [leejet/stable-diffusion.cpp#96]
I think most of the models suggest some value for clip skip. It would be very useful if it was supported.

**Comment by Green-Sky** [comment]
see automatic webui wiki https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#clip-skip (very heavy link)

> CLIP is a very advanced neural network that transforms your prompt text into a numerical representation. Neural networks work very well with this numerical representation and that's why devs of SD chose CLIP as one of 3 models involved in stable diffusion's method of producing images. As CLIP is a neural network, it means that it has a lot of layers. Your prompt is digitized in a simple way, and then fed through layers. You get numerical representation of the prompt after the 1st layer, you feed that into the second layer, you feed the result of that into third, etc, until you get to the last layer, and that's the output of CLIP that is used in stable diffusion. This is the slider value of 1. But you can stop early, and use the output of the next to last layer - that's slider value of 2. The earlier you stop, the less layers of neural network have worked on the prompt.

> Some models were trained with this kind of tweak, so setting this value helps produce better results on those models.

**Comment by FSSRepo** [comment]
> The earlier you stop, the less layers of neural network have worked on the prompt.
> 
> > Some models were trained with this kind of tweak, so setting this value helps produce better results on those models.

It's kind of like ignoring clip layers; I'm going to try doing it and see what results I get.

**Comment by leejet** [comment]
> > The earlier you stop, the less layers of neural network have worked on the prompt.
> > 
> > > Some models were trained with this kind of tweak, so setting this value helps produce better results on those models.
> 
> It's kind of like ignoring clip layers; I'm going to try doing it and see what results I get.

I think this is easy to implement, as long as you skip the specified number of layers according to the clip skip parameter when building the compute graph of cond stage model

**Comment by FSSRepo** [comment]
@imikod Can you test the skip layers function in my pull request #104? `--clip-skip N`, where `N` It is the number of final layers you want to skip.
